# Generated by Django 2.0.3 on 2018-04-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('graduado_date', models.DateField(null=True)),
                ('creditos', models.IntegerField(default=0)),
                ('promedio', models.FloatField(default=0.0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('C', 'Cursando'), ('F', 'Cursada Aprobada'), ('A', 'Materia Aprobada'), ('E', 'Equivalencia')], default='C', max_length=1)),
                ('cursada_cuat', models.CharField(blank=True, max_length=10, null=True)),
                ('cursada_date', models.DateField(blank=True, null=True)),
                ('aprobada_cuat', models.CharField(blank=True, max_length=10, null=True)),
                ('aprobada_date', models.DateField(blank=True, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('abbr_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Correlativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.Departamento')),
            ],
            options={
                'ordering': ('departamento', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='MateriaExcluyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('orientacion', models.CharField(blank=True, max_length=255, null=True)),
                ('abbr_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('min_creditos', models.IntegerField(verbose_name='Créditos')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.Carrera')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos', models.IntegerField()),
                ('cuatrimestre', models.IntegerField()),
                ('caracter', models.CharField(max_length=3)),
                ('correlativas', models.CharField(blank=True, max_length=255, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.Materia')),
                ('plancarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.PlanCarrera')),
            ],
            options={
                'ordering': ['plancarrera', 'materia'],
            },
        ),
        migrations.CreateModel(
            name='PlanOrientacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('plancarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.PlanCarrera')),
            ],
        ),
        migrations.AddField(
            model_name='correlativa',
            name='correlativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correlativa', to='facultad.PlanMateria'),
        ),
        migrations.AddField(
            model_name='correlativa',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_p', to='facultad.PlanMateria'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='plan_vigente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='facultad.PlanCarrera'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.Materia'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='plancarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad.PlanCarrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('departamento', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnomateria',
            unique_together={('user', 'materia')},
        ),
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together={('user', 'plancarrera')},
        ),
    ]
