# Generated by Django 2.0.4 on 2018-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['abbr_name']},
        ),
        migrations.AlterField(
            model_name='alumnomateria',
            name='nota',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alumnomateria',
            name='state',
            field=models.CharField(choices=[('-', 'No cursando'), ('C', 'Cursando'), ('F', 'Cursada Aprobada'), ('A', 'Materia Aprobada'), ('E', 'Equivalencia')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='short_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='plancarrera',
            name='short_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
