# Generated by Django 2.0.4 on 2018-05-02 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facultad', '0004_delete_old_model_from_the_state'),
        ('alumnos', '0001_move_a_model_and_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facultad.Materia'),
        ),
        migrations.AddField(
            model_name='materia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancarrera',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facultad.Carrera'),
        ),
        migrations.AddField(
            model_name='plancarrera',
            name='plancarrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facultad.PlanCarrera'),
        ),
        migrations.AddField(
            model_name='plancarrera',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('user', 'materia')},
        ),
        migrations.AlterUniqueTogether(
            name='plancarrera',
            unique_together={('user', 'plancarrera')},
        ),
    ]
